#!/bin/sh

# Load Xorg scripts.
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Define function to run processes
run() {
    if ! pgrep --full "$1" >/dev/null; then
        "$@" &
    fi
}

# start bar
run bar.sh

# Set wallpaper and pywal
xargs xwallpaper --stretch <~/.config/wall &

# Start Emacs daemon
# run emacs --daemon

# Run processes
run lxpolkit
run picom
run dunst
run pipewire

# Run scripts
run batterynotify
run batteryhibernate.sh
run mem.sh

xset r rate 200 50 &
xrdb -load ~/.config/X11/xresources & # Load .Xresources settings for urxvt terminals
xsetroot -cursor_name left_ptr &      # Change X shaped default cursor

while sweetdwm && type sweetdwm >/dev/null; do :; done
