import = ["/home/sweetmask/.config/alacritty/colors.toml", "/home/sweetmask/.config/alacritty/fonts.toml", "/home/sweetmask/.config/alacritty/keyboard.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 5000

[window]
dynamic_padding = false
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
